title: Yawney Hawn
description: The Yawney Hawn blog
author: Yawney Hawn
lang: en

url: "https://TOsan211.github.io"
baseurl: ""

markdown: kramdown
permalink: /posts/:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor
